baseURL = 'https://example.org/'
locale = 'en-us'
title = 'AAA'
theme = 'hugo-book'

[languages]
[languages.en]
label = "English"
contentDir = "content.en"
weight = 1
title = "CozyORM"
[languages.zh]
label = "简体中文"
contentDir = "content.zh"
weight = 2
title = "CozyORM"

[params]
bookToC = true
